NewsPapper/NewsPapper/urls.py
from django.contrib import admin
from django.urls import path, include

import news.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls'))
]

NewsPapper/news/urls.py
from django.urls import path
from .views import NewsList, NewsDetail, CreateNews, UpdateNews, DeleteNews, SearchList

app_name = 'news'

urlpatterns = [
    path('', NewsList.as_view(), name='posts'),
    path('<int:pk>', NewsDetail.as_view(), name='post_details'),
    path('add/', CreateNews.as_view(), name='post_create'),
    path('<int:pk>/edit', UpdateNews.as_view(), name='post_update'),
    path('<int:pk>/delete', DeleteNews.as_view(), name='delete_post'),
    path('search/', SearchList.as_view(), name='search_post')
]

NewsPapper/accounts/models.py
from django.db import models

# Create your models here.

NewsPapper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum

class Author(models.Model):
    userAuthor = models.OneToOneField(User, on_delete=models.CASCADE)
    userRating = models.SmallIntegerField(default=0)

    def update_rating(self):
        postValue = self.post_set.all().aggregate(summ = Sum('postRating'))
        postRating = 0
        postRating += postValue.get('summ')

        commentValue = self.userAuthor.comment_set.all().aggregate(summ = Sum('rating'))
        commentRating = 0
        commentRating += commentValue.get('summ')

        self.userRating = postRating * 3 + commentRating
        self.save()

    def __str__(self):
        return f'User: {self.userAuthor}'

class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return f'Категория: {self.name}'


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = 'NW'
    ARTICLE = 'AR'
    CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    )

    postType = models.CharField(max_length=2, choices=CHOICES, default=NEWS)
    postDate = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField(max_length=500)
    postRating = models.SmallIntegerField(default=0)

    def like(self):
        self.postRating += 1
        self.save()

    def dislike(self):
        self.postRating -= 1
        self.save()

    def preview(self):
        return self.text[:125] + '...'

    def __str__(self):
        return f'Пост за авторством: {self.author.userAuthor}, жанром: {self.postType},' \
               f' с заголовком: {self.title} и содержанием: {self.preview()} '

    def get_absolute_url(self):
        return f'/news/{self.id}'

class PostCategory(models.Model):
    postInBetween = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryInBetween = models.ForeignKey(Category, on_delete=models.CASCADE)

class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    commentDate = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'Комментарий "{self.text}", пользователя {self.commentUser}'

NewsPapper/news/forms.py
from django.forms import ModelForm
from .models import Post
from django import forms

class NewsForm(ModelForm):

    class Meta:
        model = Post
        fields = ['author', 'postType', 'postCategory', 'title', 'text']
        widgets = {
            'author': forms.Select(attrs={
                'class': 'form-control'
            }),
            'postType': forms.Select(attrs={
                'class': 'form-control'
            }),
            'postCategory': forms.SelectMultiple(attrs={
                'class': 'form-control'
            }),
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter title of post'
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Write you text in here'
            }),
        }

NewsPapper/accounts/views.py
from django.shortcuts import render

# Create your views here.

NewsPapper/news/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from .models import Post
from django.views import View
from django.utils import timezone
from django.core.paginator import Paginator
from .filters import NewsFilter
from .forms import NewsForm
from django.urls import reverse_lazy

class NewsList(ListView):
    model = Post
    template_name = 'posts/news.html'
    context_object_name = 'news'
    queryset = Post.objects.order_by('-id')
    ordering = ['-postDate']
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        return NewsFilter(self.request.GET, queryset=queryset).qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = NewsFilter(self.request.GET, queryset=self.get_queryset())
        context['choices'] = Post.CHOICES
        context['form'] = NewsForm

        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
        return super().get(request, *args, **kwargs)


class NewsDetail(DetailView):
    model = Post
    template_name = 'posts/post.html'
    context_object_name = 'news_details'


class CreateNews(CreateView):
    template_name = 'posts/adds/add.html'
    form_class = NewsForm


class UpdateNews(UpdateView):
    template_name = 'posts/adds/add.html'
    form_class = NewsForm

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class DeleteNews(DeleteView):
    model = Post
    context_object_name = "delete_news"
    template_name = 'posts/adds/delete_post.html'
    queryset = Post.objects.all()
    form_class = NewsForm
    success_url = reverse_lazy('news:posts')

class SearchList(ListView):
    model = Post
    template_name = 'posts/adds/search.html'
    context_object_name = 'posts'
    queryset = Post.objects.order_by('-id')
    ordering = ['-postDate']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = NewsFilter(self.request.GET, queryset=self.get_queryset())

        return context


# class Posts(View):
#
#     def get(self, request):
#         posts = Post.objects.order_by('-postDate')
#         pag = Paginator(posts, 10)
#         posts = pag.get_page(request.GET.get('page', 1))
#
#         context = {
#             'posts': posts
#         }
#
#         return render(request, 'posts/news.html', context)

NewsPapper/news/templates/posts/adds/add.html

{% extends 'base/default.html' %}
{% load custom_filters %}

{% block title %} Create Post {% endblock title %}
{% block content %}
    <div class="container d-flex flex-md-column align-items-center">
        <div class="w-75 p-3 d-flex justify-content-center" style="border: solid aquamarine 2px; border-radius: 5px">
                <form method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <br>
                        <input class="btn btn-success" type="submit" value="submit">
                </form>
        </div>
    </div>
{% endblock content %}

NewsPapper/news/templates/posts/adds/delete_post.html
{% extends 'base/default.html' %}
{% load custom_filters %}

{% block title %} Delete Post {% endblock title %}
{% block content %}
    <div class="container d-flex flex-md-column align-items-center">
      <h3>Are you sure you want to delete this post?</h3>
        <div class="w-75 p-3 d-flex justify-content-center" style="border: solid aquamarine 2px; border-radius: 5px">
            <br>
            <ul>
                <li> Title: {{ delete_news.title|censor|truncatewords:50 }}</li>
                <hr>
                <li>Publish Date: {{ delete_news.postDate|date:'d.m.Y H:i' }}</li>
                <hr>
                <li> Text: {{ delete_news.text|censor|truncatewords:50 }}</li>
                <hr>
                <li> Author: {{ delete_news.author.userAuthor }}</li>
            </ul>
        </div>
        <form method="POST">
          {% csrf_token %}
          <br>
          <input class="btn btn-success" type="submit" value="delete">
        </form>
    </div>
{% endblock content %}

NewsPapper/news/templates/posts/adds/paginator.html
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a style="text-decoration: none" href="?page=1">First&nbsp</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a>{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.paginator.num_pages }}">&nbsp</a>
            <a style="text-decoration: none" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

        {% endif%}

NewsPapper/news/templates/posts/adds/post_details.html
{% extends 'base/default.html' %}
{% load custom_filters %}

{% block title %} Post Details {% endblock title %}
{% block content %}
    <div class="card d-flex flex-md-column align-items-center">
        <div class="card-header" style="border: solid aquamarine 2px; border-radius: 5px">
            <br>
            <h3>Title: {{ news_details.title|censor|truncatewords:50 }}</h3>
                <hr>
                <div>Publish Date: {{ news_details.postDate|date:'d.m.Y H:i' }}</div>
                <hr>
        </div>
        <div class="card-body">Text: {{ news_details.text|censor|truncatewords:50 }}</div>
    </div>
{% endblock content %}



NewsPapper/news/templates/posts/adds/search.html
{% extends 'base/default.html' %}
{% load custom_filters %}

{% block title %} Search {% endblock title %}
{% block content %}
    <div class="container d-flex flex-md-column align-items-center">
        <br>
        <form method="GET" action="{% url 'news:posts' %}">
            {{ filter.form }}
            <input type="submit" class="btn btn-primary" value="Find">
        </form>
    </div>
<!--    {% if filter %}-->
<!--    <table class="table">-->
<!--                <tr>-->
<!--                    <td style="font-weight: bold">Title</td>-->
<!--                    <td style="font-weight: bold">Publish Date</td>-->
<!--                    <td style="font-weight: bold">Text</td>-->
<!--                    <td style="font-weight: bold">Edit</td>-->
<!--                    <td style="font-weight: bold">Delete</td>-->
<!--                </tr>-->
<!--                {% for post in filter.qs %}-->
<!--                    <tr>-->
<!--                        <td><a href="{% url 'news:post_details' post.id %}">{{ post.title|censor }}</a></td>-->
<!--                        <td>{{ post.postDate|date:'d.m.Y' }}</td>-->
<!--                        <td>{{ post.text|truncatewords:50|censor }}</td>-->
<!--                        <td>-->
<!--                            <a href="{% url 'news:post_update' post.id %}">Edit</a>-->
<!--                        </td>-->
<!--                        <td><a href="{% url 'news:delete_post' post.id %}">Delete</a></td>-->
<!--                    </tr>-->
<!--                {% endfor %}-->
<!--            </table>-->
<!--    {% endif %}-->

{% endblock content %}





NewsPapper/news/templates/posts/news.html
{% extends 'base/default.html' %}
{% load custom_filters %}

{% block title %} DjangoDjenerics {% endblock title %}

{% block content %}

    <div class="container d-flex flex-md-column align-items-center">
        <h2>Total number of posts {{ filter.qs|length }}</h2>
        <br>
        {% if news %}
            <table class="table">
                <tr>
                    <td style="font-weight: bold">Title</td>
                    <td style="font-weight: bold">Publish Date</td>
                    <td style="font-weight: bold">Text</td>
                    <td style="font-weight: bold">Edit</td>
                    <td style="font-weight: bold">Delete</td>
                </tr>
                {% for post in news %}
                    <tr>
                        <td><a href="{% url 'news:post_details' post.id %}">{{ post.title|censor }}</a></td>
                        <td>{{ post.postDate|date:'d.m.Y' }}</td>
                        <td>{{ post.text|truncatewords:50|censor }}</td>
                        <td>
                            <a href="{% url 'news:post_update' post.id %}">Edit</a>
                        </td>
                        <td><a href="{% url 'news:delete_post' post.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <h2>Sorry, the posts are missing</h2>
        {% endif %}
    </div>
<div class="container d-flex flex-md-row justify-content-center paginator">
{% include 'posts/adds/paginator.html' %}
</div>

    <div class="container d-flex flex-md-column align-items-center">
        <br>
        <form action="{% url 'news:post_create' %}">
            <input type="submit" class="btn btn-primary" value="Add post">
        </form>
    </div>
{% endblock content %}

NewsPapper/news/templates/posts/post.html
{% extends 'base/default.html' %}
{% load custom_filters %}

{% block title %} Selected post {% endblock title %}
{% block content %}
    <div class="container d-flex flex-md-column align-items-center">
        <div class="w-75 p-3 d-flex justify-content-center" style="border: solid aquamarine 2px; border-radius: 5px">
            <br>
            <ul>
                <li> Title: {{ news_details.title|censor|truncatewords:50 }}</li>
                <hr>
                <li> Publish Date: {{ news_details.postDate|date:'d.m.Y H:i' }}</li>
                <hr>
                <li> Text: {{ news_details.text|censor|truncatewords:50 }}</li>
            </ul>
        </div>
    </div>
    <div class="container d-flex flex-md-row justify-content-around">
        <a href="{% url 'news:post_update' news_details.id %}">Edit</a>
        <a href="{% url 'news:delete_post' news_details.id %}">Delete</a>
    </div>
{% endblock content %}



NewsPapper/templates/base/default.html
{% load static %}
{% load custom_filters %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">

    

    <!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/product.css' %}" rel="stylesheet">
  </head>
  <body>
    
<header class="site-header sticky-top py-1">
  <nav class="container d-flex flex-column flex-md-row justify-content-between">
    <a class="py-2" href="/news" aria-label="Product">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto" role="img" viewBox="0 0 24 24"><title>{% block title %} {% endblock title %}</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
    </a>
    <a class="py-2 d-none d-md-inline-block" href="/news">News</a>
    <a class="py-2 d-none d-md-inline-block" href="/news/search">Search</a>
    <a class="py-2 d-none d-md-inline-block" href="/news/2">Product</a>
  </nav>
</header>

<main>
    {% block content %}
    {% endblock content %}
</main>
</body>